### ISSUE TITLE
Ansible Automation Hub Certification and dcnm contact information

### ISSUE THREAD

**Issue by alisonlhart** [CiscoDevNet/ansible-dcnm#134]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Ansible Partner Engineering team has received the Cisco dcnm v2.0.1 collection on Automation Hub. Before approval, there are a number of errors in the import log that need to be resolved. The log can be viewed on Automation Hub. The log should present solutions and/or explanations for all errors shown. We can provide recommendations on how to resolve these issues as well. For direct contact with the Ansible PE team to discuss recommendations for the dcnm collection, please reach out to ansiblepartners@redhat.com. You can also respond to this issue with contact information and we will reach out. 

### DCNM version

* V 2.0.1

**Comment by mikewiebe** [comment]
@alisonlhart Thanks for reaching out!  We saw those and have fixed the errors here

https://github.com/CiscoDevNet/ansible-dcnm/pull/133

Once we finish testing we will create a new collection tarball and upload.

**Comment by alisonlhart** [comment]
@mikewiebe That's great. Everything else collection-structure-wise looks good to go. If you or someone on the team could shoot us an email at the alias [ansiblepartners@redhat.com](mailto:ansiblepartners@redhat.com) when you upload next, we'll send a notification when it's approved. 

I'll close this issue out now. We just wanted to reach out and ensure all is moving smoothly. Thanks!
