### ISSUE TITLE
Remove  DHCP RELAY IP with cisco.dcnm.dcnm_networK

### ISSUE THREAD

**Issue by sissi48** [CiscoDevNet/ansible-dcnm#155]
We have a problem when we create a network with the ansible module : cisco.dcnm.dcnm_network on DCNM.
when we ran this script we had a strange behavior, The first run went well, it created the networks on the multi-site fabric correctly. When we did a second test again, the script timed out and removed all DHCP RELAY IP from all networks in the fabric  MULTI-SITES.

    - name: Create vlan L2
      cisco.dcnm.dcnm_network:
        fabric: "{{ Fabric }}"
        config:
        - net_name: "{{ item.network_name  }}"
          vlan_id:  "{{ item.vlan_id }}"
          vlan_name: "{{ item.vlan_name  }}"
          int_desc: "{{ item.description }}"
          mtu_l3intf: 9216
          is_l2only: yes

      when: item.type == "L2"
      with_items:
        - "{{ result.ansible_facts.vlans }}"

    - name: Create vlan L3
      cisco.dcnm.dcnm_network:
        fabric: "{{ Fabric }}"
        config:
        - net_name: "{{ item.network_name }}"
          vrf_name: "{{ item.vrf }}"
          vlan_id:  "{{ item.vlan_id }}"
          gw_ip_subnet: "{{ item.gw_ip }}"
          int_desc: "{{ item.description  }}"
          vlan_name: "{{ item.vlan_name  }}"      
          mtu_l3intf: 9216
      when: item.type == "L3"
      with_items:
        - "{{ result.ansible_facts.vlans }}"

Have you any idea ?why we have this behavior?

**Comment by praveenramoorthy** [comment]
@sissi48, thanks for raising this issue. Will check and work on fix for this issue.

**Comment by kba39** [comment]
Hi,

We have faced issues when using ansible dcnm network module.
Actually, when we use this module to deploy overlays, the current DHCP configuration is deleted on all fabrics in a Multi Site Domain. So it generates KOs in production.

@praveenramoorthy, any updates ?

**Comment by praveenramoorthy** [comment]
@sissi48 @kba39. I tried to repro this issue in my local setup unsuccessfully. My understanding is that you have l2/l3 networks configured on a MSD fabric using ansible and when you run the same playbook again you are loosing DHCP relay configs in those networks. Can you please share more details on python, ansible and collections versions you are using? Can you share the playbook execution logs? If you cannot share it here, you can share it over a gist a a secret too. W.r.t timeout, if you have a scaled fabric, and if you are operating with default timeouts, increasing connect and command timeout will help.

**Comment by kba39** [comment]
Thank u praveenramoorthy for your comments.

Please find below versions:
python 3.8.10
ansible 2.10.15
cisco.dcnm collection  1.2.3

Regarding the logs, I had to re play the playbook on a lab with verbose option.

**Comment by sissi48** [comment]
Thank you praveenramoorthy for your feedback.
Below versions that we use:
Python 3.6.8
ansible 2.10.11
cisco.dcnm            1.2.0 .
when we executed the playbook, we had no log output for a while and we had to kill him

**Comment by shyamkapadia** [comment]
I believe custom Network/Network extension profiles may be used that is causing the issue. Can those be shared?

**Comment by praveenramoorthy** [comment]
@sissi48 @kba39, I still working on the repro, can you please share DCNM version too?

**Comment by kba39** [comment]
@praveenramoorthy, thank you for your updates.

DCNM version is 11.5(1)

**Comment by sissi48** [comment]
we use DCNM version 11.5(2)

**Comment by kba39** [comment]
Hello team,

It seems that every time we provide wrong inputs in the network module fields (like 'ethernet' despite of Ethernet), It generates an error and the rollback of the task is played. 
I have reproduced the same issue in a lab (2 leaves in vPC). May be every time the rollback is automatically played by the playbook, it doesn't generate the previous dhcp config.

I tested many use case and dhcp config is only deleted with the case describe above.

Please find below an output message from my playbook.
*****************************************************
msg:
    DATA:
      MyNetwork_30777_JAN-[XXXXX/LF-01]: Invalid Interfaces in XXXXX. Invalid interfaces areethernet1/26
    MESSAGE: OK
    METHOD: POST
    REQUEST_PATH: https://10.43.252.95:443/rest/top-down/fabrics/DCI-ACHERES-TRAPPES/networks/attachments
    RETURN_CODE: 200
    ROLLBACK_RESULT: SUCCESS - Attempted rollback of the task has succeeded
*****************************************************

**Comment by kba39** [comment]
Hello team,

It seems that every time we provide wrong inputs in the network module fields (like 'ethernet' despite of Ethernet), It generates an error and the rollback of the task is played.
I have reproduced the same issue in a lab (2 leaves in vPC). May be every time the rollback is automatically played by the playbook, it doesn't generate the previous dhcp config.

I tested many use case and dhcp config is only deleted with the case describe above.

Please find below an output message from my playbook.

msg:
DATA:
MyNetwork_30777_JAN-[XXXXX/LF-01]: Invalid Interfaces in XXXXX. Invalid interfaces areethernet1/26
MESSAGE: OK
METHOD: POST
REQUEST_PATH: [https://xxxxx:443/rest/top-down/fabrics/xxxxx/networks/attachments](https://xxxxx/rest/top-down/fabrics/xxxxx/networks/attachments)
RETURN_CODE: 200
ROLLBACK_RESULT: SUCCESS - Attempted rollback of the task has succeeded

**Comment by dsx1123** [comment]
@kba39 do you mind sharing the playbook and steps to reproduce this issue?

**Comment by kba39** [comment]
Hello team,

Please find below the playbook with one basic task. 

Please mind that all leaves are in vPC mode. So to deploy a network for interfaces, you have to include 
the 2 members of the vPC pair.

To reproduce the issue 
1. Configure manually a dhcp server/vrf for a network (into one fabric)
2. Make sure the interfaces you will configure are in switched mode
3. Into the playbook, fill in one the port form (switch2 for example) with 'ethernet1/id' instead of 'Ethernet1/id'

==================================================================================
- name: DHCP issue
  hosts: dcnm_poc
  gather_facts: no
  vars:
    ansible_command_timeout: 1000
    ansible_connect_timeout: 1000
  tasks:

  - name: Extension vlan MyNetwork_30777_JAN  
    cisco.dcnm.dcnm_network:
      fabric: MSD                                      
      state: merged
      config:
      - net_name: MyNetwork_30777_JAN                    
        vrf_name: MyVRF_6000
        net_id: 30777
        net_template: Default_Network_Universal
        net_extension_template: Default_Network_Extension_Universal
        vlan_id: 777                      
        attach:
        - ip_address: switch1@ip
          ports: ['Ethernet1/26']
          deploy: true
        - ip_address: switch2@ip
          ports: ['ethernet1/26']

==================================================================================
versions of the stack

Python 3.8.10
pip 22.2.2
ansible 2.10.17
cisco.dcnm 2.1.0

**Comment by dsx1123** [comment]
@kba39 thank you, will get back asap.

**Comment by praveenramoorthy** [comment]
@sissi48 @kba39 Thanks a lot for sharing the steps. I am able to reproduce this issue in our lab. Will work on the fix and let you know once it is ready.

**Comment by sissi48** [comment]
@praveenramoorthy Can you tell me how  did you to reproduce the problem?

**Comment by praveenramoorthy** [comment]
@sissi48 I followed the same steps and playbook as mentioned by @kba39 last week. My MSD setup initially did not have vpc mode enabled for the leaves but last week I had enabled it between leaves in my setup. For some reason without vpc mode rollback was not being invoked, but with vpc I see rollback is being invoked and was hitting same issue as yours(DHCP relay IP and Vrf were reset in the networks in member fabrics).

**Comment by kba39** [comment]
Hello team,

Thank you for the updates.

Could you please confirm from which version the bug is fixed ?

Best Regards

**Comment by praveenramoorthy** [comment]
@kba39, The fix is approved and will be merge with develop branch. It will be part of upcoming release.

**Comment by PCluzz** [comment]
@praveenramoorthy : can you please tell us when you plan to plan to release the next version with this fix ?

**Comment by praveenramoorthy** [comment]
@PCluzz, the next version will be released by the end of next week.

**Comment by mikewiebe** [comment]
Fixed in release https://github.com/CiscoDevNet/ansible-dcnm/releases/tag/2.2.0
