### ISSUE TITLE
Policy delete deploying pending configs for  all switched in the fabric as opposed to only declared switches ip.

### ISSUE THREAD

**Issue by samurato** [CiscoDevNet/ansible-dcnm#163]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Ansible Version and collection version

ansible 2.10.5, 
### DCNM version

* V11.5(2)

### Affected module(s)

* cisco.dcnm.dcnm_policy

### Ansible Playbook

```yaml
- name: Delete no password strength policy
  cisco.dcnm.dcnm_service_policy:
    fabric: "{{ targeted_fabric }}"
    state: deleted 
    config:
      - name: no_pass_strength  # name is mandatory
      - switch:
          - ip: "{{ targeted_ip }}"
```

### Debug Output

``` 
(automation-env) : ~/code/to-git/cisco-dcnm-module-playbooks$ ansible-playbook -i inventory policy.yml -vvv
ansible-playbook 2.10.5
config file = /home/code/to-git/cisco-dcnm-module-playbooks/ansible.cfg
configured module search path = ['/home/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /var/venv/automation-env/lib/python3.8/site-packages/ansible
executable location = /var/venv/automation-env/bin/ansible-playbook
python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
Using /home/code/to-git/cisco-dcnm-module-playbooks/ansible.cfg as config file
host_list declined parsing /home/code/to-git/cisco-dcnm-module-playbooks/inventory as it did not pass its verify_file() method
script declined parsing /home/code/to-git/cisco-dcnm-module-playbooks/inventory as it did not pass its verify_file() method
auto declined parsing /home/code/to-git/cisco-dcnm-module-playbooks/inventory as it did not pass its verify_file() method
Parsed /home/code/to-git/cisco-dcnm-module-playbooks/inventory inventory source with ini plugin
[WARNING]: While constructing a mapping from /home/code/to-git/cisco-dcnm-module-playbooks/policy.yml, line 7, column 5, found a duplicate dict key (targeted_fabric). Using last defined value only.
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: policy.yml *****************************************************************************************************************************************************************************************
1 plays in policy.yml

PLAY [dcnm_controllers] **************************************************************************************************************************************************************************************
META: ran handlers

TASK [leaf-switch-deploy : DCNM Delete no password strength-check Policy] ************************************************************************************************************************************
task path: /home/code/to-git/cisco-dcnm-module-playbooks/roles/leaf-switch-deploy/tasks/main.yml:3
included: /home/code/to-git/cisco-dcnm-module-playbooks/roles/leaf-switch-deploy/tasks/custom-delete-password-policy.yml for 10.10.10.10 => (item={'targeted_ip': '10.10.20.10', 'leaf': True, 'tcam_model_leaf': True})

TASK [leaf-switch-deploy : Delete no password strength policy] ***********************************************************************************************************************************************
task path: /home/code/to-git/cisco-dcnm-module-playbooks/roles/leaf-switch-deploy/tasks/custom-delete-password-policy.yml:1
<10.10.10.10> ESTABLISH LOCAL CONNECTION FOR USER: sam
<10.10.10.10> EXEC /bin/sh -c '( umask 77 && mkdir -p "echo /home/.ansible/tmp/ansible-local-728699ci1g9qf4"&& mkdir "echo /home/.ansible/tmp/ansible-local-728699ci1g9qf4/ansible-tmp-1661914438.7802823-728714-49864876881276" && echo ansible-tmp-1661914438.7802823-728714-49864876881276="echo /home/.ansible/tmp/ansible-local-728699ci1g9qf4/ansible-tmp-1661914438.7802823-728714-49864876881276" ) && sleep 0'
<10.10.10.10> Attempting python interpreter discovery
<10.10.10.10> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<10.10.10.10> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /var/venv/automation-env/lib/python3.8/site-packages/ansible_collections/cisco/dcnm/plugins/modules/dcnm_policy.py
<10.10.10.10> PUT /home/.ansible/tmp/ansible-local-728699ci1g9qf4/tmpyqaq7sg5 TO /home/.ansible/tmp/ansible-local-728699ci1g9qf4/ansible-tmp-1661914438.7802823-728714-49864876881276/AnsiballZ_dcnm_policy.py
<10.10.10.10> EXEC /bin/sh -c 'chmod u+x /home/.ansible/tmp/ansible-local-728699ci1g9qf4/ansible-tmp-1661914438.7802823-728714-49864876881276/ /home/.ansible/tmp/ansible-local-728699ci1g9qf4/ansible-tmp-1661914438.7802823-728714-49864876881276/AnsiballZ_dcnm_policy.py && sleep 0'
<10.10.10.10> EXEC /bin/sh -c '/usr/bin/python3 /home/.ansible/tmp/ansible-local-728699ci1g9qf4/ansible-tmp-1661914438.7802823-728714-49864876881276/AnsiballZ_dcnm_policy.py && sleep 0'


```

### Expected Behavior

Should only impact the desired switches configs to be deployed but switches in the whole fabric is impacted not just the declared switch

### Actual Behavior

As per documentation it should only impact the selected switch

### Steps to Reproduce

Have multiple switches in a fabric with policies added but not deployed.
Try to delete a policy for only one switch in the fabric. This will deploy pending configs for all switches in the fabric

**Comment by praveenramoorthy** [comment]
@samurato thanks for raising this issue. Can you check this behavior in release 2.1.1? This issue has been fixed through PR #156 in that release.

**Comment by samurato** [comment]
Hello @praveenramoorthy, The Policy is not being deleted. DCNM Shows its Progressing and Failed and retried it multiple times.

**Comment by mmudigon** [comment]
@samurato, can you please share the playbook you used? We will try this locally and see what the issue is. Also if you possible, can you let us know what the exact error is?

**Comment by samurato** [comment]
Hello @mmudigon playbook is show above
- name: Delete no password strength policy
  cisco.dcnm.dcnm_service_policy:
    fabric: "{{ targeted_fabric }}"
    state: deleted 
    config:
      - name: no_pass_strength  # name is mandatory
      - switch:
          - ip: "{{ targeted_ip }}"

**Comment by samurato** [comment]
replace with any ip and dcnm fabric

**Comment by mmudigon** [comment]
Hi @samurato,

Is this a policy that you created? I don't find any policy with template name "no_pass_strength" in 11.5 DCNM server. If you have created the template "no_pass_strength" and a policy based on this template, please let me have the template creation playbook also. I will create the template and the policy and then check the delete operation.

**Comment by samurato** [comment]
could you please check password_no_strength policy. Not sure if it deafult in DCNM, If not I will pass you the template format.

**Comment by mmudigon** [comment]
Hi @Samurato,

Found  the template
Will try to create a policy with this and will try to delete the same
Will let you know my observations

**Comment by mmudigon** [comment]
Hi @Samurato,

I tried the same here locally. I did not see any issues. Can you please let me know what is the error that you see. You can find the error at the top of the screen in Fabric view (next to "save and deploy" button). Please see what the error is and let me know.

**Comment by samurato** [comment]
Hello, Looks like the blast radius has narrowed down to swtich level
https://github.com/CiscoDevNet/ansible-dcnm/issues/179
Raised to address that issue
