### ISSUE TITLE
Add cisco.dcnm collection to docs.ansible.com

### ISSUE THREAD

**Issue by adealdag** [CiscoDevNet/ansible-dcnm#178]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This collection is not listed under the Ansible documentation page. Add the documentation in the website under Cisco namespace:
https://docs.ansible.com/ansible/latest/collections/cisco/index.html

### New or Affected modules(s):

N/A

### DCNM version

N/A

### Potential ansible task config

N/A

### References

**Additional context**

**Comment by dsx1123** [comment]
@adealdag These are the collection documented on the ansible website, NDFC was introduced after. We are not planning to move the document to ansible website.
