### ISSUE TITLE
Port Channel Interface Creation Issue

### ISSUE THREAD

**Issue by Jae-cisco** [CiscoDevNet/ansible-dcnm#183]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Ansible Version and collection version

     Ansible 2.13.1 
     Collection 2.4.0

### DCNM version

     NDFC 12.1.1

### Affected module(s)

* dcnm_XXXXX

### Ansible Playbook

     #Create a single port channel interface on Leaf-1 and Leaf 2's eth1/10 port in fabric "test" 
  
  - name: Create port channel interfaces
    cisco.dcnm.dcnm_interface: #&pc_merge
      fabric: test
      state: merged                         # only choose from [merged, replaced, deleted, overridden, query]
      config:
        - name: po300                       # should be of the form po<port-id>
          type: pc                          # choose from this list [pc, vpc, sub_int, lo, eth]
          switch:
            - "Leaf-01_01,02"                 # provide the switch information where the config is to be deployed
          deploy: true                      # choose from [true, false]
          profile:
            admin_state: true               # choose from [true, false]
            mode: trunk                     # choose from [trunk, access, l3, monitor]
            members:                        # member interfaces
              - eth1/10
            pc_mode: 'active'               # choose from ['on', 'active', 'passive']
            bpdu_guard: true                # choose from [true, false, no]
            port_type_fast: true            # choose from [true, false]
            mtu: jumbo                      # choose from [default, jumbo]
            allowed_vlans: none             # choose from [none, all, vlan range]
            cmds:                           # Freeform config
              - no shutdown
            description: "port channel acting as trunk"

```yaml
# Copy-paste your anisble playbook here 
```

### Debug Output

     Cannot find switch's name Leaf-01_01,02 

### Expected Behavior

      Should've selected Leaf 01 and Leaf 02 switch for port channel interface in vpc pair.
      In my NDFC, there exists a vpc pair "Leaf-01_01,02" that consist of two leaf switches - leaf 01,02. 
      However, Ansible port channel interface collection cannot find this switch when executing playbook.

### Actual Behavior

      Can select leaf switch 01 and 02 when making port channel interface via Ansbile collection in NDFC.

**Comment by mmudigon** [comment]
@Jae-cisco 

Hi,
The correct way to create a port channel interface po300 on switches Leaf-01 and Leaf-02 would be as follows:

name: Create port channel interfaces
cisco.dcnm.dcnm_interface: #&pc_merge
fabric: test
state: merged # only choose from [merged, replaced, deleted, overridden, query]
config:
- name: po300 # should be of the form po
type: pc # choose from this list [pc, vpc, sub_int, lo, eth]
**switch:
- Leaf-01 # provide the switch information where the config is to be deployed
- Leaf-02 # provide the switch information where the config is to be deployed**
deploy: true # choose from [true, false]
profile:
admin_state: true # choose from [true, false]
mode: trunk # choose from [trunk, access, l3, monitor]
members: # member interfaces
- eth1/10
pc_mode: 'active' # choose from ['on', 'active', 'passive']
bpdu_guard: true # choose from [true, false, no]
port_type_fast: true # choose from [true, false]
mtu: jumbo # choose from [default, jumbo]
allowed_vlans: none # choose from [none, all, vlan range]
cmds: # Freeform config
- no shutdown
description: "port channel acting as trunk"

Please make the correction and try it again. Let me know if you still see any issues

Regards
Mallik
