### ISSUE TITLE
NDFC-Ansible: Staging the config/policy by Ansible causes leaf config change

### ISSUE THREAD

**Issue by smukkavi** [CiscoDevNet/ansible-dcnm#192]
The objective is to use the Ansible scripts only for all the operational changes and not from the NDFC GUI nor the leafs and spines directly.

Using the cisco.dcnm.dcnm_policy ansible module as shown below this description when using deploy=false, state=deleted still causes the switch (device) to be touched/config is deployed. In this case the hostname removed. I did not try all the other configuration policies. 

But however, the "state=merged" works as expected with the config pending in NDFC to be deployed to the switch (device). We would like the state=deleted to also function in the same way without touching the device when deploy=false, it should cause the config-pending state, until manually deployed on the NDFC.
=============================
Ansible script used for staging the config - (state=deleted, deploy=false) , running the playbook causes the switch configuration to be changed.

==============================
    - name: "Delete host_11_1 config"
      cisco.dcnm.dcnm_policy:
        fabric: "{{ switch.FABRIC }}"
        state: deleted
        deploy: false
        config:
          - name: host_11_1
            create_additional_policy: false
 
          - switch:
            - ip: "{{ switch.MGMT_IP }}"
 
 
    - name: Apply host_11_1 config
      cisco.dcnm.dcnm_policy:
        fabric: "{{ switch.FABRIC }}"
        state: merged
        deploy: false
        config:
          - name: host_11_1
            create_additional_policy: false
            policy_vars:
              SWITCH_NAME: "{{ switch.SWITCH_NAME }}"
 
          - switch:
            - ip: "{{ switch.MGMT_IP }}"
 =============================

**Comment by mikewiebe** [comment]
Thanks for opening this issue @smukkavi.  We are working on a fix.

Here is the PR for your reference: https://github.com/CiscoDevNet/ansible-dcnm/pull/191

**Comment by mikewiebe** [comment]
Fixed in release https://github.com/CiscoDevNet/ansible-dcnm/releases/tag/3.0.0
