### ISSUE TITLE
NDFC-Ansible: The VRF script has limitations

### ISSUE THREAD

**Issue by smukkavi** [CiscoDevNet/ansible-dcnm#193]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Customer likes to use Ansible to push the configurations to stage them on NDFC (deploy=flase) and then deploy them from NDFC during the maintenance window. It is not ideal to pass certain parameters from Ansible script and the remaining parameters from the NDFC (the parameters that are missing on the Ansible script).  The NDFC is to hold the staged policies (from ansible) and then deploy when required.
The VRF script (ndfc_vrf ansible script downloaded from cisco.dcnm.dcnm_policy) has limited information to post on the NDFC, it is not possible to supply the following parameters in the script and run the Ansible playbook. 

Only the VRF name and VRF id are passed to the NDFC, but following information is missing or not feasible to supply from the script.
=======
Vlan ID, the other tabs in the same VRF definition - General Parameters, Advanced and Route-target tabs
========

Because of this limitation, there is requirement to login to the NDFC to pass these parameters on the GUI.

### New or Affected modules(s):

ndfc_vrf ansible script downloaded from cisco.dcnm.dcnm_policy) 

### DCNM version

* V 12.1.1e

### Potential ansible task config

```yaml
# Copy-paste your ansible playbook
```

### References

**Additional context**

**Comment by smukkavi** [comment]
![vrf-definition](https://user-images.githubusercontent.com/123026397/215223017-9219cae1-23a2-4b85-ac6b-7e33d9114a59.png)

**Comment by praveenramoorthy** [comment]
@smukkavi, Thanks for this SR, we are already working on supporting all the vrf  parameters in playbook. It will be part of our upcoming release. There are a bunch of General and Advanced parameters already supported, you can check it out. Thanks

**Comment by mikewiebe** [comment]
PR in review for this: https://github.com/CiscoDevNet/ansible-dcnm/pull/208

**Comment by praveenramoorthy** [comment]
Fixed as part of #208
