### ISSUE TITLE
NDFC-Ansible: VRF Policy- Ansible Playbook supplied VLAN ID is missing on NDFC GUI.

### ISSUE THREAD

**Issue by smukkavi** [CiscoDevNet/ansible-dcnm#194]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Problem Description:

Customer likes to use Ansible to push the configurations to stage them on NDFC (with "deploy=flase") and then deploy them from NDFC during the maintenance window. Using the VRF script (ndfc_vrf ansible script downloaded from cisco.dcnm.dcnm_policy),
customer is passing the vlan_id as a parameter from the Ansible script ,but vlan_id is not populated on the NDFC, it remains blank and asks to click on the propose VLAN in the GUI, which causes a randomly available vlan or the next available VLAN but not the vlan that is supplied from the ansible script. 

### DCNM version

* V 12.1.1e

### Affected module(s)

![vrf-definition](https://user-images.githubusercontent.com/123026397/215885231-0ee41248-7a3d-4cd7-aac1-836536f2584c.png)
![VRF-Definition-Missing VLAN ID](https://user-images.githubusercontent.com/123026397/215885503-7b5d967e-3601-432c-94cd-61565e0cae17.png)

* dcnm_XXXXX

### Ansible Playbook

```yaml
# Copy-paste your anisble playbook here 
```

**Comment by praveenramoorthy** [comment]
@smukkavi Thanks for raising this issue. Will check it out and work on it.

**Comment by praveenramoorthy** [comment]
Fixed as part of #208
