### ISSUE TITLE
NDFC: Ansible module to create new fabric using easy_fabric template with all parameters

### ISSUE THREAD

**Issue by smukkavi** [CiscoDevNet/ansible-dcnm#195]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Customer wants to create/modify a fabric in NDFC with the Easy_Fabric template using Ansible. The Ansible module should be able to supply all the parameters that could be supplied via the GUI. The ansible script should be able provide all the parameters in the script itself or from separate files for the referring variables.

### New or Affected modules(s):

* dcnm_XXXXX

### DCNM version

* V 12.1.1e

### Potential ansible task config

The intent of this module is to use the Ansible playbook directly to create new fabric or modify the values in the existing fabric. This will prevent the user to access the NDFC GUI and create new fabric or modify exist fabric that may cause accidentally provide wrong information or fat-fingering the values which will take long to troubleshoot later. All parameters in the tabs of the screen attached should be possible to supply by Ansible script.

```yaml
# Copy-paste your ansible playbook
```

### References

**Additional context**

![New Fabric Parameters](https://user-images.githubusercontent.com/123026397/218277235-e408bd44-7e76-4f0a-9c7c-a54f82f66b9b.png)

**Comment by dsx1123** [comment]
duplicate #85
