### ISSUE TITLE
NDFC:  Ansible module dcnm_network.py cannot supply secondary IP for SVI.

### ISSUE THREAD

**Issue by smukkavi** [CiscoDevNet/ansible-dcnm#196]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### DCNM version

* V 15.1.1e

### Affected module(s)

dcnm_network.py

* dcnm_XXXXX

dcnm_network.py

```yaml
# Copy-paste your anisble playbook here 
```

### Expected Behavior

Secondary IP address assignment using the script dcnm_network.py, just like how the NDFC GUI supports it for SVI.

### Actual Behavior

The dcnm_network.py module in ansible_collections/cisco/dcnm/plugins/modules also doesn't support all parameters that could be supplied via the GUI when configuring a network in a Fabric in NDFC. (example secondary gateway IP address/mask on svi)

**Comment by praveenramoorthy** [comment]
Fixed as part of #208
