### ISSUE TITLE
support poap when add new switches

### ISSUE THREAD

**Issue by dsx1123** [CiscoDevNet/ansible-dcnm#27]
### feature request
add poap support on dcnm_inventory module

### current behavior
When add new switches to fabric, currently dcnm_inventory only support using mgmt ip address to register switches to fabric, user could use built-in poap function of dcnm to onboarding new switch. this feature request is to add poap support under dcnm_inventory module.

**Comment by micruzz82** [comment]
This would also help in day 0 bring up of fabric.

**Comment by mikewiebe** [comment]
https://github.com/CiscoDevNet/ansible-dcnm/pull/166

**Comment by praveenramoorthy** [comment]
POAP support added to `dcnm_inventory` module through #166 and is part of release 2.4.0
