### ISSUE TITLE
Creating / Merging Interfaces Fail with DCNM ver 10.5(1)

### ISSUE THREAD

**Issue by Tessier-Ashp001** [CiscoDevNet/ansible-dcnm#41]
ansible 2.10.6
  config file = /root/dev/dcnm-ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/envs/dcnm-ansible/lib/python3.6/site-packages/ansible
  executable location = /root/envs/dcnm-ansible/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

DCNM Version 10.5(1)

playbook: see attached 
[merge-loopback.txt](https://github.com/CiscoDevNet/ansible-dcnm/files/6062882/merge-loopback.txt)

Expected Result: 
TASK [Create loopback interfaces] to return code 200

Actual Result:
```
TASK [Create loopback interfaces] **********************************************************************************************************
fatal: [10.X.X.X]: FAILED! => {"changed": false, "msg": {"DATA": [{"column": 0, "entity": "", "line": 0, "message": "Interface type is not valid", "reportItemType": "ERROR"}], "MESSAGE": "Internal Server Error", "METHOD": "POST", "REQUEST_PATH": "https://10.X.X.X:443/rest/globalInterface", "RETURN_CODE": 500}}
```

**Comment by Tessier-Ashp001** [comment]
Update:


I think ansible is sending the following in the data field of the POST request (which is built from .ansible/collections/ansible_collections/cisco/dcnm/plugins/modules/dcnm_interface.py):

{
  "policy": "int_loopback_11_1",
  "interfaces": [
    {"interfaceType": "INTERFACE_LOOPBACK",
      "nvPairs": {
      "ROUTE_MAP_TAG": "",
      "CONF": "no shutdown",
      "IP": "99.99.99.99",
      "V6IP": "",
      "INTF_VRF": "",
      "ADMIN_STATE": "true",
      "INTF_NAME": "Loopback95",
      "DESC": "loopback interface 95 configuration"
      },
      "ifName": "Loopback95",
      "serialNumber": "FHEUD36383",
      "fabricName": "my-fabric"}
      ],
      "skipResourceCheck": "true"
}


From the latest DCNM API documentation, what is should look like is:

{
  "policy": "int_loopback_11_1",
  "interfaceType": "INTERFACE_LOOPBACK",
  "interfaces": [
    {
      "serialNumber": "FHEUD36383",
      "ifName": "Loopback95",
      "nvPairs": {
      "ROUTE_MAP_TAG": "",
      "CONF": "no shutdown",
      "IP": "99.99.99.99",
      "V6IP": "",
      "INTF_VRF": "",
      "ADMIN_STATE": "true",
      "INTF_NAME": "Loopback95",
      "DESC": "loopback interface 95 configuration"
      }
    }
  ]
}

**Comment by Tessier-Ashp001** [comment]
resolved in develop branch...

**Comment by mikewiebe** [comment]
@Tessier-Ashp001 Thanks for opening this issue.  Just for clarification, were you testing with the latest release version from Ansible galaxy but then discovered that this is resolved in the `develop` branch?

**Comment by Tessier-Ashp001** [comment]
Hi @mikewiebe That's it exactly. Ansible Galaxy gave me the 1.0.0 version I think, which looks to be from last September. So I just reinstalled the collection specifying the develop branch this time. It's working fine now.

Thanks!
