### ISSUE TITLE
Getting misleading message from dcmm module 

### ISSUE THREAD

**Issue by asharma1304** [CiscoDevNet/ansible-dcnm#46]
I was getting the following error messages when i ran my playbooks against valid fabrics - in my setup, "MSD_Fabric_East" and 'Site-A' are valid fabrics. However, my issue was really a simple IP connectivity issue between the Ansible control node and DCNM. Let me know If you need more info. I am running Ansible 2.10 and latest Python3 versions. DCNM is running 11.5(1). 

(python3-ansible-venv) [administrator@asharma-linux-js55 Config_FP-VXLAN-Fabric]$ ansible-playbook -i inventory setup_fabric.yml 

PLAY [Setup VXLAN fabric configuration for FlexPod MetroCluster CVD] ******************************************************

TASK [Query fabric for list of Spine and Leaf switches] *******************************************************************
fatal: [192.168.160.140]: FAILED! => {"changed": false, "msg": "Unable to find inventories under fabric: MSD_Fabric_East"}

PLAY RECAP ****************************************************************************************************************
192.168.160.140            : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

(python3-ansible-venv) [administrator@asharma-linux-js55 Config_FP-VXLAN-Fabric]$ vi setup_fabric.yml 
(python3-ansible-venv) [administrator@asharma-linux-js55 Config_FP-VXLAN-Fabric]$ ansible-playbook -i inventory setup_fabric.yml 

PLAY [Setup VXLAN fabric configuration for FlexPod MetroCluster CVD] ******************************************************

TASK [Query fabric for list of Spine and Leaf switches] *******************************************************************
fatal: [192.168.160.140]: FAILED! => {"changed": false, "msg": "Unable to find inventories under fabric: Site-A"}

PLAY RECAP ****************************************************************************************************************
192.168.160.140            : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

(python3-ansible-venv) [administrator@asharma-linux-js55 Config_FP-VXLAN-Fabric]$ 

******* Detailed Log ******

(python3-ansible-venv) [administrator@asharma-linux-js55 Config_FP-VXLAN-Fabric]$ ansible-playbook -i inventory -vvv setup_fabric.yml 
ansible-playbook 2.10.7
  config file = None
  configured module search path = ['/home/administrator/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/administrator/python3-ansible-venv/lib64/python3.6/site-packages/ansible
  executable location = /home/administrator/python3-ansible-venv/bin/ansible-playbook
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
No config file found; using defaults
host_list declined parsing /home/administrator/Config_FP-VXLAN-Fabric/inventory as it did not pass its verify_file() method
script declined parsing /home/administrator/Config_FP-VXLAN-Fabric/inventory as it did not pass its verify_file() method
auto declined parsing /home/administrator/Config_FP-VXLAN-Fabric/inventory as it did not pass its verify_file() method
Parsed /home/administrator/Config_FP-VXLAN-Fabric/inventory inventory source with ini plugin
redirecting (type: action) cisco.dcnm.dcnm_inventory to cisco.dcnm.dcnm
redirecting (type: action) cisco.dcnm.dcnm_inventory to cisco.dcnm.dcnm
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: setup_fabric.yml ************************************************************************************************
1 plays in setup_fabric.yml

PLAY [Setup VXLAN fabric configuration for FlexPod MetroCluster CVD] ******************************************************
META: ran handlers
redirecting (type: action) cisco.dcnm.dcnm_inventory to cisco.dcnm.dcnm

TASK [Query fabric for list of Spine and Leaf switches] *******************************************************************
task path: /home/administrator/Config_FP-VXLAN-Fabric/setup_fabric.yml:11
redirecting (type: action) cisco.dcnm.dcnm_inventory to cisco.dcnm.dcnm
<192.168.160.140> ESTABLISH LOCAL CONNECTION FOR USER: administrator
<192.168.160.140> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/administrator/.ansible/tmp/ansible-local-157047_i0u24kb `"&& mkdir "` echo /home/administrator/.ansible/tmp/ansible-local-157047_i0u24kb/ansible-tmp-1616973903.5716214-157053-120667932400862 `" && echo ansible-tmp-1616973903.5716214-157053-120667932400862="` echo /home/administrator/.ansible/tmp/ansible-local-157047_i0u24kb/ansible-tmp-1616973903.5716214-157053-120667932400862 `" ) && sleep 0'
Using module file /home/administrator/.ansible/collections/ansible_collections/cisco/dcnm/plugins/modules/dcnm_inventory.py
<192.168.160.140> PUT /home/administrator/.ansible/tmp/ansible-local-157047_i0u24kb/tmpgn4g5sfu TO /home/administrator/.ansible/tmp/ansible-local-157047_i0u24kb/ansible-tmp-1616973903.5716214-157053-120667932400862/AnsiballZ_dcnm_inventory.py
<192.168.160.140> EXEC /bin/sh -c 'chmod u+x /home/administrator/.ansible/tmp/ansible-local-157047_i0u24kb/ansible-tmp-1616973903.5716214-157053-120667932400862/ /home/administrator/.ansible/tmp/ansible-local-157047_i0u24kb/ansible-tmp-1616973903.5716214-157053-120667932400862/AnsiballZ_dcnm_inventory.py && sleep 0'
<192.168.160.140> EXEC /bin/sh -c 'python /home/administrator/.ansible/tmp/ansible-local-157047_i0u24kb/ansible-tmp-1616973903.5716214-157053-120667932400862/AnsiballZ_dcnm_inventory.py && sleep 0'
<192.168.160.140> EXEC /bin/sh -c 'rm -f -r /home/administrator/.ansible/tmp/ansible-local-157047_i0u24kb/ansible-tmp-1616973903.5716214-157053-120667932400862/ > /dev/null 2>&1 && sleep 0'
fatal: [192.168.160.140]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "config": null,
            "fabric": "Site-A",
            "state": "query"
        }
    },
    "msg": "Unable to find inventories under fabric: Site-A"
}
^C [ERROR]: User interrupted execution
(python3-ansible-venv) [administrator@asharma-linux-js55 Config_FP-VXLAN-Fabric]$ 

********** playbook module ******
    - name: Query fabric for list of Spine and Leaf switches
      cisco.dcnm.dcnm_inventory: 
        fabric: Site-A
        state: query
      register: result

**Comment by mikewiebe** [comment]
@asharma1304 Thanks for bringing this issue to our attention.  We are working on a fix.
