### ISSUE TITLE
L2 Checkbox while creating a network

### ISSUE THREAD

**Issue by AnirudhPangri** [CiscoDevNet/ansible-dcnm#72]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Ansible Version and collection version

ansible 2.10.3     collection: 1.1.1
### DCNM version

* 11.4

### Affected module(s)

* dcnm_networks

While creating a network on DCNM GUI, we have an option to create it without a VRF by checking on the L2 checkbox.
Can this be achieved using this collection?

Any pointers will be appreciated. Thanks.

**Comment by mikewiebe** [comment]
@AnirudhPangri Thanks for opening this issue.  We don't currently support this but we are adding support for this in the near future.

**Comment by mikewiebe** [comment]
Addressed by pr https://github.com/CiscoDevNet/ansible-dcnm/pull/74
