### ISSUE TITLE
Installation Documentation wrong

### ISSUE THREAD

**Issue by 020003** [CiscoDevNet/ansible-dcnm#8]
Hi,

first of all thanks for the awesome collection.

I just found a small issue on the documentation.
`ansible-galaxy collection install cisco.dcnm` 
Doesn't work by default. I tested it on multiple hosts and ansible versions just to be sure.
The basic requirements.yml documentation shows version 0.9.0.
If somebody just copies this in his requirements.yml it will also not work. 
It is need to append the correct version aswell.
No big Issue but maybe it prevents some new ansible users on pursuing this track since they get frustrated.

collections:
  - name: cisco.dcnm
    version: 0.9.0-dev4

**Comment by mikewiebe** [comment]
Thanks for letting us know about this doc issue!  We will address this in the current develop branch and publish a new version soon.

**Comment by mikewiebe** [comment]
Resolved by https://github.com/CiscoDevNet/ansible-dcnm/commit/d447f18a051141b9b5970d77d3d6c1e5f5e5c6d2
