### ISSUE TITLE
Fix documentation issues in modules

### ISSUE THREAD

**Issue by praveenramoorthy** [CiscoDevNet/ansible-dcnm#84]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### DCNM version

* V 1.2.0

### Affected module(s)

* all modules

### Ansible Playbook

```yaml
# Copy-paste your anisble playbook here 
```

**Comment by mikewiebe** [comment]
Resolved by https://github.com/CiscoDevNet/ansible-dcnm/pull/88
